[package]
name = "kowalski"
version = "0.1.0"
edition = "2024"
authors = ["Jaro <yarenty@gmail.com>"]
description = "A Rust-based agent for interacting with Ollama models"
license = "MIT"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }
config = "0.15"
dirs = "6.0"
toml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7", features = ["v4", "serde"] }
pdf-extract = "0.8"