[package]
name = "kowalski"
version = "0.2.0"
edition = "2024"
description = "A Rust-based agent for interacting with Ollama models"
license = "MIT"
authors = ["yarenty <yarenty@gmail.com>"]
repository = "https://github.com/yarenty/kowalski"
homepage = "https://github.com/yarenty/kowalski"
readme = "README.md"
categories = [
    "api-bindings",
    "asynchronous",
    "network-programming",
    "text-processing",
    "science"
]
keywords = [
    "AI",
    "agent",
    "chat",
    "llm",
    "ollama"
]

[dependencies]
# HTTP and async
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Serialization and data formats
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Configuration and system
config = "0.15"
dirs = "6.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7", features = ["v4", "serde"] }

# Document processing
pdf-extract = "0.8"

# Web browsing and scraping
scraper = "0.23"           # HTML parsing and scraping
url = "2.5"               # URL parsing and manipulation
fantoccini = "0.19"       # Headless browser automation (replaces headless_chrome)
select = "0.6"            # CSS selector based scraping

# Search engines
# google-apis = "5.0"       # Google Custom Search API
# async-google-apis-common = "0.4.0"
duckduckgo_rs = "0.0.1"     # Fixed package name for DuckDuckGo API client

# Data processing
html2md = "0.2"          # HTML to Markdown conversion
cached = "0.55"          # Result caching
regex = "1.10"           # Pattern matching
quick-xml = "0.37"       # XML processing
encoding_rs = "0.8"      # Character encoding support

# Storage
sled = "0.34"            # Embedded database for caching
rusqlite = { version = "0.34", features = ["bundled"] }  # SQLite for local storage
flate2 = "1.0"          # Compression for cached data

# Rate limiting and utilities
governor = "0.8"         # Rate limiting
urlencoding = "2.1.0"

# Logging
log = "0.4"
env_logger = "0.11"

[[example]]
name = "model_manager"
path = "examples/model_manager.rs"

[[example]]
name = "academic_research"
path = "examples/academic_research.rs"

[[example]]
name = "web_research"
path = "examples/web_research.rs"

[[example]]
name = "web_search"
path = "examples/web_search.rs"

[[example]]
name = "web_dynamic"
path = "examples/web_dynamic.rs"

[[example]]
name = "web_static"
path = "examples/web_static.rs"

[[example]]
name = "general_chat"
path = "examples/general_chat.rs"
